spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false


  s3:
    bucket: ${S3_BUCKET}
  region:
    static: ${REGION}

  # redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      readonly-host: ${REDIS_READONLY_HOST}
      readonly-port: ${REDIS_READONLY_PORT}

# orm 로그 파라미터 바인딩 설정
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace  # orm 로그 파라미터 바인딩 설정
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSSz,Asia/Seoul # 로그 시간 설정

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

images:
  preview: ${PREVIEW_IMAGE}

